---
- name: Create admin group
  ansible.builtin.group:
    name: admin
    gid: 1000
  become: true

- name: Create admin user
  ansible.builtin.user:
    name: admin
    uid: 1000
    group: admin
    append: true
    groups: sudo
    shell: /bin/bash
    password: "{{ users_admin_password | password_hash('yescrypt') }}"
    update_password: on_create
  become: true

- name: Set public key for admin user
  ansible.posix.authorized_key:
    user: admin
    key: "{{ users_admin_public_key }}"
  become: true

- name: Create deploy group
  ansible.builtin.group:
    name: deploy
  become: true

- name: Create deploy user
  ansible.builtin.user:
    name: deploy
    group: deploy
    append: true
    groups: sudo
    shell: /bin/bash
    password: "!"
  become: true

- name: Set public key for deploy user
  ansible.posix.authorized_key:
    user: deploy
    key: "{{ users_deploy_public_key }}"
  become: true

- name: Sudo without password for deploy user
  ansible.builtin.copy:
    dest: /etc/sudoers.d/deploy
    content: "deploy ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: "0440"
    validate: /usr/sbin/visudo -cf %s
  become: true
