---
- name: Deploy homelab server
  hosts: homelab

  tasks:
    - name: Run docker role
      ansible.builtin.include_role:
        name: docker

    # - name: Run homelab role
    #   ansible.builtin.include_role:
    #     name: homelab
