---
- name: Deploy ru proxy server
  hosts: ru_proxy

  tasks:
    - name: Run docker role
      ansible.builtin.include_role:
        name: docker

    - name: Run ru proxy role
      ansible.builtin.include_role:
        name: ru_proxy
