services:
  traefik:
    image: traefik:3.7.13
    container_name: traefik
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    ports:
      - 192.168.1.10:80:80
      - 192.168.1.10:443:443
      - 192.168.1.10:443:443/udp
    volumes:
      - /mnt/docker-volumes/traefik/traefik/config/traefik.yaml:/etc/traefik
