services:
  caddy:
    image: caddy:2.11.4-alpine
    container_name: caddy
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./index.html:/srv/index.html:ro
      - caddy_sock:/var/run/caddy
      - caddy_data:/data
      - caddy_config:/config
      - subscription-server_sock:/var/run/subscription-server
    network_mode: none
    environment:
      - PATH_PREFIX=${PATH_PREFIX}

  hysteria:
    image: tobyxdd/hysteria:v2.12.2
    container_name: hysteria
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./hysteria.yaml:/etc/hysteria.yaml:ro
      - caddy_sock:/var/run/caddy
      - hysteria_acme:/acme
    networks:
      - hysteria
    command: ["server", "-c", "/etc/hysteria.yaml"]

  warp:
    image: caomingjun/warp:2026.6.880.0-2.12.0
    container_name: warp
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - WARP_SLEEP=5
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - hysteria
    volumes:
      - warp_data:/var/lib/cloudflare-warp

  subscription-server:
    container_name: subscription-server
    image: ghcr.io/awesfdawe/subscription-server:0.0.4
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    volumes:
      - ./config.yaml:/config/config.yaml
      - ./users.yaml:/config/users.yaml
      - ./hysteria2.json:/config/hysteria2.json
      - subscription-server_sock:/var/run/subscription-server
      - subscription_server_data:/data
    networks:
      - subscription_server

networks:
  hysteria:
    driver: bridge
  subscription_server:
    driver: bridge

volumes:
  caddy_sock:
  caddy_data:
  caddy_config:
  hysteria_acme:
  warp_data:
  subscription-server_sock:
  subscription_server_data:
